# Generated by Django 5.1.3 on 2024-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_created_by_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='solution',
            field=models.TextField(default='print()'),
            preserve_default=False,
        ),
    ]
