# Generated by Django 5.1.3 on 2024-12-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_completedtask_is_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
