# Generated by Django 5.1.3 on 2024-12-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.forum'),
            preserve_default=False,
        ),
    ]
