version: "3.3"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/static:/var/www/staticfiles
      - ./backend/media:/var/www/media
      - letsencrypt:/etc/letsencrypt
      - webroot:/var/www/certbot
    depends_on:
      - backend

  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  certbot:
    image: certbot/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - webroot:/var/www/certbot

volumes:
  letsencrypt:
  webroot: