[tool.black]
line-length = 79
skip-string-normalization = true
extend-exclude = 'migrations'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
skip = ["venv"]
skip_glob = ["*/migrations/*"]
src_paths = ["backend"]
force_sort_within_sections = true